LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := crypto

LOCAL_C_INCLUDES := $(LOCAL_PATH)/inc/$(TARGET_ARCH_ABI)

LOCAL_SRC_FILES := lib/$(TARGET_ARCH_ABI)/libcrypto.a

LOCAL_EXPORT_C_INCLUDES := $(LOCAL_C_INCLUDES)

include $(PREBUILT_STATIC_LIBRARY)


include $(CLEAR_VARS)

LOCAL_MODULE := ssl

LOCAL_C_INCLUDES := $(LOCAL_PATH)/inc/$(TARGET_ARCH_ABI)

LOCAL_SRC_FILES := lib/$(TARGET_ARCH_ABI)/libssl.a

LOCAL_CFLAGS := -DOPENSSL_NO_UI_CONSOLE

LOCAL_EXPORT_C_INCLUDES := $(LOCAL_C_INCLUDES)

include $(PREBUILT_STATIC_LIBRARY)