/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_duoyi_dyhttp_DuoyiHttpApi */

#ifndef _Included_com_duoyi_dyhttp_DuoyiHttpApi
#define _Included_com_duoyi_dyhttp_DuoyiHttpApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_duoyi_dyhttp_DuoyiHttpApi
 * Method:    DyHttpInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_duoyi_dyhttp_DuoyiHttpApi_DyHttpInit
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
